### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by liach** [Minecraft-GoodTime/GregTech-Localization-Chinese#1]
@JAVA10086 你把翻译文件的格式搞错了，顺序也错了，最重要的是不能撤销改动。请重新在stable分支进行改动。

**Comment by 1156407698** [comment]
我有点怀疑直接机翻复制粘贴0.0

**Comment by liach** [comment]
问题是格式全部损坏了，而且有些已经翻译的东西重新变成了英文。

**Comment by 1156407698** [comment]
那就撤销吧

**Comment by JAVA10086** [comment]
我应该懂了，可能是我开启WPS文字的时候损坏的，我深表歉意。。。。。
                                                             2015.2.20 by：JAVA10086






------------------ 原始邮件 ------------------
发件人: "liach"<notifications@github.com>; 
发送时间: 2015年2月20日(星期五) 中午11:19
收件人: "Minecraft-GoodTime/GregTech-Localization-Chinese"<GregTech-Localization-Chinese@noreply.github.com>; 
抄送: "God-death"<2251357245@qq.com>; 
主题: Re: [GregTech-Localization-Chinese] Formatting issue (#1)




问题是格式全部损坏了，而且有些已经翻译的东西重新变成了英文。

**Comment by 1156407698** [comment]
那就赶紧弄好😌

**Comment by liach** [comment]
在新的branch里面弄，幸亏git版本管理器好，在叫stable的branch编辑就行了。

**Comment by wc7086** [comment]
弄好没

**Comment by liach** [comment]
Resolved in branch stable.
