### ISSUE TITLE
Another Project

### ISSUE THREAD

**Issue by liach** [Minecraft-GoodTime/GregTech-Localization-Chinese#2]
https://github.com/TehporP/GregTech6-Translation-Project
Have a look?! @1156407698

**Comment by 1156407698** [comment]
So？

**Comment by liach** [comment]
Ask someone who's in teamTF and ask for more information.

**Comment by 3TUSK** [comment]
https://github.com/TehporP/GregTech6-Translation-Project/commit/95511238889a4fa4435d8d5d6314bbb06c234b7e
